development:
  adapter: postgresql
  encoding: utf8
  database: storge_dev
  pool: 5
  host: localhost
  port: 5432
  template: template0
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: utf8
  database: storge_test
  pool: 5
  host: localhost
  port: 5432
  template: template0
  username: postgres
  password: 
